# fly.toml app configuration file generated for cspaper-org on 2024-08-05T19:10:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cspaper-org'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8000
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
